name: Stoplight

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  Stoplight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm install

      - name: Push to Stoplight
        run: |
          npx @stoplight/cli@6 push --ci-token ${TOKEN_STOPLIGHT} --url ${YOUR_STOPLIGHT_URL}
