
name: StopLight

on: 
    push:
        branches:
          - main
    pull_request:
        branches:
            - main

jobs: 
    StopLight:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
        
            - name: Using node.js
              uses: actions/setup-node@v2
              with: 
                node-version: 16.x

            - name: Install and Build
              run: |
                npm install

            - name: Stoplight
              run: |
                npx @stoplight/cli@6 push --ci-token 99ba8aa3-ea20-4ebe-be9a-9a1e4de06d0d -- url https://bruno-dela-val.stoplight.io/


